### PR TITLE
Add additional dependencies to RTD build

### PR DESCRIPTION
**Pull request by rosteen**
This is needed so HSTaXe wheel will build in the RTD build. Also useful to test RTD build triggering on Pull Request, which it should do now.

### CODE REVIEW

**Review by larrybradley — APPROVED** [review]

**Comment by rosteen** [comment]
Slowly working though the errors here...I would convert to draft, but I'm not sure if the RTD builds would trigger then. I might ping you for a re-review when it's actually working @larrybradley.

**Comment by larrybradley** [comment]
`wcs.h` comes from `wcstools` (or `wcslib`) (http://tdc-www.harvard.edu/wcstools/).  I'm not sure if there is an apt package for this.

**Comment by rosteen** [comment]
I included `wcstools` and it didn't complain about installing it with apt...I'll try `wcslib`.

**Comment by rosteen** [comment]
Hmm, `wcslib-dev` didn't fix the error. I wonder if RTD really needs to build the package at all to build the docs, it would be nice to not have to worry about all the C packages. I know there is `autodocs-mock-imports` to "pretend" to import things without building them, but I'm not sure that would work on the actual base package that you're building docs for.

**Comment by rosteen** [comment]
Actually, I think I can specify the conda installs needed like I would locally. I'll explore that path.

**Review by pllim — COMMENTED** [review]
Why do you need conda to build its *documentation*? What do you need from conda that you cannot find via pip or apt?

**Comment by pllim** [comment]
I would argue that you don't need a custom extension to do figures. Sphinx has its own figure directive.

https://github.com/spacetelescope/hstaxe/blob/bf0c9ed367a390f90e0907cfd56617808a7111f0/docs/conf.py#L91

**Comment by rosteen** [comment]
> Why do you need conda to build its _documentation_? What do you need from conda that you cannot find via pip or apt?

When I installed wcstools with apt, the build was still erroring on not being able to find `wcs.h`...figured I'd try the conda install that I know works locally.

**Comment by pllim** [comment]
What is wcstools ? Do you really need it to build documentation?

**Comment by rosteen** [comment]
If you have a way to get the docs to build on readthedocs without it trying to build the package itself and thus hitting errors from the C things it relies on I'm happy to do so, I just didn't see a way to do that and am thus trying to debug the build.

**Comment by rosteen** [comment]
I don't care about the API docs at this point (I don't think they've ever been available anywhere, although I could be wrong), but regardless what I'm trying to say is I don't know how to stop it building the package even if I don't want the API docs.

**Comment by larrybradley** [comment]
I've wondered if `hstaxe` really needs the `wcstools` package or if it really only needs `wcslib`.  `wcslib` is available on conda-forge (https://anaconda.org/conda-forge/wcslib), so that would eliminate the only `astroconda` dependency.

**Comment by larrybradley** [comment]
It's required `wcstools`.  It's a C-only package so the Python version doesn't matter.

**Comment by pllim** [comment]
You are currently asking RTD to install the package:

https://github.com/spacetelescope/hstaxe/blob/bf0c9ed367a390f90e0907cfd56617808a7111f0/.readthedocs.yml#L17

If you remove that and change https://github.com/spacetelescope/hstaxe/blob/main/docs/conf.py to not call hstaxe (like the `package` stuff and `sys.insert` stuff), theoretically you can run `sphinx-build` on just the RST files without having to build hstaxe.

**Comment by pllim** [comment]
But conda tries to match Python versions, no? If you are running on Python 3.10, why would conda search for builds for Python 3.7?

Also, if your required dependency only installable from astroconda, how are you even running CI on this package?

**Comment by rosteen** [comment]
> Also, if your required dependency only installable from astroconda, how are you even running CI on this package?

Bold of you to assume that CI is being run on this package...

**Comment by larrybradley** [comment]
`conda install wcstools -c https://ssb.stsci.edu/astroconda -y` works fine for me in a Python 3.10 environment.

**Comment by pllim** [comment]
Maybe you should hold off on documentation until the more critical problem of relying on something that is exclusive on astroconda is solved...

**Comment by rosteen** [comment]
Closing this in favor of #37, which builds the html docs (but excludes the API docs - as we've seen here, getting the package to build on RTD is a huge pain).

**Pull request closed without merging**
