### PR TITLE
Rename readme back to .md

### PR DESCRIPTION
**Pull request by rosteen**
Apparently `hatch` build fails if it doesn't find a `README.md` file from which to extract metadata.

### CODE REVIEW

**Comment by rosteen** [comment]
I don't know how I ended up with all these commits here 😵

**Comment by rosteen** [comment]
Whew, got the commits cleaned up, I might just merge without a second approval since I confirmed it fixes the build locally.

**Comment by nphathi** [comment]
Ok, will try the installation again.

Thanks,
-Nimish

**Comment by ofek** [comment]
??? just set https://github.com/spacetelescope/hstaxe/blob/c6a73c8211c3eac71f0aa6eb4125f5be227ae7c4/pyproject.toml#L9

**Comment by rosteen** [comment]
> ??? just set

Clearly I hadn't had enough caffeine that morning 😆

**Pull request merged**
