### PR TITLE
Improve wcstools linkage

### PR DESCRIPTION
**Pull request by jhunkeler**
:magic_wand:

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
Does this package not have CI set up? 😱 

I am not sure I am brave enough to test this. So, I'll excuse myself from reviewing.

**Comment by larrybradley** [comment]
The build fails for me (on macos):
```
      ld: library not found for -l/Users/lbradley/local/conda/envs/hstaxe_test
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      make[1]: *** [Makefile:634: aXe_SEX2GOL] Error 1
      make[1]: Leaving directory '/Users/lbradley/files/dev/repos/dev/hstaxe/cextern/src'
      make: *** [Makefile:412: install-recursive] Error 1
      Command '['make', 'install']' returned non-zero exit status 2.
      [end of output]
```

**Comment by rosteen** [comment]
I see a different failure (it still doesn't find the `wcstools` files in their `include` subdirectory at `/Users/rosteen/opt/anaconda3/envs/hstaxe/include/wcstools`

```
Making install in src
      make[1]: Entering directory '/Users/rosteen/projects/hstaxe/cextern/src'
      gcc -DHAVE_CONFIG_H -I. -I..    -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include//Users/rosteen/opt/anaconda3/envs/hstaxe -g -O2 -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include -I/Users/rosteen/opt/anaconda3/envs/hstaxe/include//Users/rosteen/opt/anaconda3/envs/hstaxe -MT aXe_SEX2GOL.o -MD -MP -MF .deps/aXe_SEX2GOL.Tpo -c -o aXe_SEX2GOL.o aXe_SEX2GOL.c
      In file included from aXe_SEX2GOL.c:9:
      In file included from ./spc_sex.h:8:
      ./spc_CD.h:11:10: fatal error: 'wcs.h' file not found
      #include "wcs.h"
               ^~~~~~~
      1 error generated.
      make[1]: *** [Makefile:729: aXe_SEX2GOL.o] Error 1
      make[1]: Leaving directory '/Users/rosteen/projects/hstaxe/cextern/src'
      make: *** [Makefile:412: install-recursive] Error 1
      Command '['make', 'install']' returned non-zero exit status 2.
      [end of output]
```

**Comment by jhunkeler** [comment]
I was only focused on the autotools implementation. Give this a try and let me know if compiling it manually explodes or not.

## with pkgconfig
```
conda create -n axebuild -c conda-forge compilers cfitsio gsl wcstools pkgconfig
conda activate axebuild
export PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig
cd hstaxe/cextern
./autogen.sh
./configure
make
```

## and again without pkgconfig
```
unset PKG_CONFIG_PATH
make distclean
./configure --with-wcstools=$CONDA_PREFIX --with-wcstools-libname=wcstools
make
```

**Comment by larrybradley** [comment]
@jhunkeler Manual compiling works for me with and without pkgconfig.

**Comment by pllim** [comment]
Your instruction above is missing autoconf install? I am trying it out on WSL2 and I get this:

```
ERROR:  Unable to locate GNU Autoconf.
```

And you did it! I was trying to avoid installing this thing all these years but you got me to try to install it.

**Comment by jhunkeler** [comment]
You can install the autotools deps in your conda environment ```conda install autoconf automake m4 aclocal``` ... I think that's all it needs.

**Comment by rosteen** [comment]
@pllim the install instructions on the repo README include:

```
conda install gsl cfitsio make automake autoconf libtool pkg-config -y
conda install wcstools -c conda-forge -y
```

**Comment by pllim** [comment]
Okay, I did try `sudo apt-get` (Debian Buster) but I got some error and then conda can't see it. .

```
ldconfig: Can't link /usr/lib/wsl/lib/libnvoptix_loader.so.1 to libnvoptix.so.1
ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link
```

I cannot get aclocal from conda-forge so I excluded that. But after that I have to install libtool from conda-forge too. And then it built.

**Comment by pllim** [comment]
But where are the executables? I cannot find them.

**Comment by pllim** [comment]
Not sure why this file was modified after build:

```diff
--- a/cextern/config.h.in
+++ b/cextern/config.h.in
@@ -82,8 +82,7 @@
 /* Define to 1 if the system has the type `_Bool'. */
 #undef HAVE__BOOL

-/* Define to the sub-directory in which libtool stores uninstalled libraries.
-   */
+/* Define to the sub-directory where libtool stores uninstalled libraries. */
```

**Comment by jhunkeler** [comment]
Ha! I think I was having a moment earlier. `config.h.in` is a generated `autogen.sh` (`autoconf`). I'll ditch the file from the repo.

**Comment by rosteen** [comment]
> Ha! I think I was having a moment earlier.

I also thought I was going crazy due to this 😆.

I got the `pip` install working with an added line to the `hatch_build` file, I'll go ahead and open a PR to add that here.

**Comment by rosteen** [comment]
@jhunkeler Would you rebase this to `master` when you remove that file please?

**Comment by pllim** [comment]
When this works, you should push this out to conda-forge and run away. Just sayin'.

**Comment by jhunkeler** [comment]
> But where are the executables? I cannot find them.

For a real build you'd set the installation prefix (default is `/usr/local`) and run the `install` target, like:

```
./configure --prefix=$CONDA_PREFIX
make install
```

To see what _would_ be installed into the prefix, you'd do something like this:
```
make install DESTDIR=/tmp/install_test
find /tmp/install_test
```

**Comment by rosteen** [comment]
@jhunkeler  See https://github.com/jhunkeler/hstaxe/pull/1. Thanks so much for this update!

**Comment by pllim** [comment]
Ah, ok. So it is like hstcal. Gotcha.

**Review by rosteen — APPROVED** [review]

**Comment by rosteen** [comment]
I'm going to merge this and open up a small follow-up PR with the hatch_build fix.

**Pull request merged**
